name: Test

on:
  push:
    branches:
      - master
      - release-v*
  pull_request: {}
  workflow_dispatch: {}


jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: compile # will run `yarn compile` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint # will run `yarn lint` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test # will run `yarn test` command

      - name: OS update
        run: sudo add-apt-repository universe && sudo apt-get update
      - name: Install pip
        run: apt install python3-pip -y
      - name: Install slither
        run: pip3 install slither-analyzer
      - name: Install solc-select
        run: pip3 install solc-select
      - name: Install Solidity compiler
        run: solc-select install 0.8.11
      - name: Run slither
        run: slither . --ignore-compile
